### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by Pazus** [Pazus/utPLSQL#1]
@jgebal, @Shoelace I've posted the pull request to the v3 baranch.

If you have any suggestion and comments on the implementation, please, let me know.

**Comment by jgebal** [comment]
@Pazus All nice. I've added some small improvements - check your repo for PR.

**Comment by jgebal** [comment]
I've just noticed that [the code in current state](https://github.com/Pazus/utPLSQL/blob/object-types-design/source/types/ut_test.tpb#L56) is using the setup/teardown definition separately for each test.

This means we can use separate setup for test.
What I'm missing is a package level setup/teardown and a suite level setup teardown.

My general idea would be to allow following call:
ut_suite(the_schema) - run all test packages within given schema
within each package, run all procedures that are tests
The suite is the schema and consists of sub-suites (context) for each test package
Each sub-suite consists of test procedures in the package.
setup/teardown can be defined for schema level suite, for package suite and for test in a package.

To define a test as well as schema/package/test level setup and teardown, procedure level annotations could be used.

Examples

```
package test_package
   /*
   @suite_setup test_package
   */
   procedure a_suite_setup

   /*
   @test_setup a_test
   */
   procedure a_test_setup
   /*
   @test nice and long name of the test
   */
   procedure a_test
   ...
end;
```
